go_import_path: github.com/bbiao/go-imagequant

language: go
go:
  - 1.12.x
  - tip

os:
  - linux
dist: bionic
sudo: false

before_install:
  - sudo apt-get -y install libimagequant-dev

matrix:
  allow_failures:
    - go: tip

gobuild_args: -v

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - go build ./...
